Load dataframes

In [1]:
import pandas as pd

xlsum_train = pd.read_json('persian_XLSum_v2.0/persian_train.jsonl', lines=True)
xlsum_test = pd.read_json('persian_XLSum_v2.0/persian_test.jsonl', lines=True)
print(f"previous size of train dataset:{len(xlsum_train.index)}")
print(f"previous size of test dataset:{len(xlsum_test.index)}")

previous size of train dataset:47251
previous size of test dataset:5906

In [3]:
train_df = xlsum_train[xlsum_train['summary'].apply(len) > 120].loc[:,['text', 'summary']]
test_df = xlsum_test[xlsum_test['summary'].apply(len) > 120].loc[:,['text', 'summary']]
print(f"next size of train dataset:{len(train_df.index)}")
print(f"next size of test dataset:{len(test_df.index)}")

next size of train dataset:35232
next size of test dataset:4306

Split dataframes

In [4]:
train_df_1 = train_df.iloc[:10000]
train_df_2 = train_df.iloc[10000:20000]
train_df_3 = train_df.iloc[20000:30000]
train_df_4 = train_df.iloc[30000:]

In [5]:
train_df_4

,text,summary
39888,اين کنسرت روز يکشنبه با يادی از ادوارد سعيد مو...,نوازندگان عرب و اسرائيلی کنسرت مشترکی به رهبری...
39890,هرچند دانشمندان از مدت ها قبل بر اين موضوع تاک...,آمريکا با استناد به کاسته شدن از سطح يخ های من...
39891,"فرانسوا فیون نامزد اصلی حزب راست میانه ""جمهوری...",مقامات قضایی در فرانسه گفته‌اند که دامنه تحقیق...
39892,حال ساخت سد هراز در محدوده محل دفن زباله شهرست...,بیش از یک دهه است که سدسازی در برخی از مناطق ا...
39893,دو نفر از دستگیرشدگان از طلبه های یک مدرسه اسل...,مقامات پاکستان می گویند چهار نفر به اتهام دست ...
...,...,...
47026,آقای نتانیاهو هشدار داد که انفجار بعدی در لبنا...,بنیامین نتانیاهو، نخست وزیر اسرائیل، در نطق خو...
47029,به گفته وزارت کشور عراق و به گزارش خبرگزاری فر...,به رغم اقدامات امنيتی و با وجود تشکيل اولين جل...
47030,اجرای شب نخست لطفی به سه بخش تقسیم می شد. ابتد...,محمد رضا لطفی ،آهنگساز و نوازنده تار و سه تار ...
47031,مقام های فلسطينی اين حمله انتحاری را محکوم کرد...,پليس اسرائيل می گويد يک بمبگذاری انتحاری در خا...
47033,خوزه مانوئل باروسو گفت که اعتبار اتحادیه اروپا...,رئیس کمیسیون اروپایی می گوید چند روز آینده که ...

Save dataframes as csv files

In [12]:
train_df_1.to_csv('./Data/train_data_1.csv', index=False)
train_df_2.to_csv('./Data/train_data_2.csv', index=False)
train_df_3.to_csv('./Data/train_data_3.csv', index=False)
train_df_4.to_csv('./Data/train_data_4.csv', index=False)
test_df.to_csv('./Data/test_data.csv', index=False)

Load csv files to check

In [9]:
df1 = pd.read_csv('./Data/train_data_1.csv')
df2 = pd.read_csv('./Data/train_data_2.csv')
df3 = pd.read_csv('./Data/train_data_3.csv')
df4 = pd.read_csv('./Data/train_data_4.csv')

In [10]:
df4

,text,summary
0,اين کنسرت روز يکشنبه با يادی از ادوارد سعيد مو...,نوازندگان عرب و اسرائيلی کنسرت مشترکی به رهبری...
1,هرچند دانشمندان از مدت ها قبل بر اين موضوع تاک...,آمريکا با استناد به کاسته شدن از سطح يخ های من...
2,"فرانسوا فیون نامزد اصلی حزب راست میانه ""جمهوری...",مقامات قضایی در فرانسه گفته‌اند که دامنه تحقیق...
3,حال ساخت سد هراز در محدوده محل دفن زباله شهرست...,بیش از یک دهه است که سدسازی در برخی از مناطق ا...
4,دو نفر از دستگیرشدگان از طلبه های یک مدرسه اسل...,مقامات پاکستان می گویند چهار نفر به اتهام دست ...
...,...,...
5227,آقای نتانیاهو هشدار داد که انفجار بعدی در لبنا...,بنیامین نتانیاهو، نخست وزیر اسرائیل، در نطق خو...
5228,به گفته وزارت کشور عراق و به گزارش خبرگزاری فر...,به رغم اقدامات امنيتی و با وجود تشکيل اولين جل...
5229,اجرای شب نخست لطفی به سه بخش تقسیم می شد. ابتد...,محمد رضا لطفی ،آهنگساز و نوازنده تار و سه تار ...
5230,مقام های فلسطينی اين حمله انتحاری را محکوم کرد...,پليس اسرائيل می گويد يک بمبگذاری انتحاری در خا...
5231,خوزه مانوئل باروسو گفت که اعتبار اتحادیه اروپا...,رئیس کمیسیون اروپایی می گوید چند روز آینده که ...